http {
    include mime.types;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    server {
        listen 80;
        server_name www.$BASE_URL $BASE_URL;

        location ^~ /.well-known/acme-challenge/ {
            alias /app/letsencrypt/acme/.well-known/acme-challenge/;
            default_type text/plain;
        }

        location / {
            return 301 https://$BASE_URL$request_uri;
        }
    }
}

events {}