server {
    listen 80;
    server_name $OLD_BASE_URL www.$OLD_BASE_URL;

    location ^~ /.well-known/acme-challenge/ {
        alias /app/letsencrypt/acme/.well-known/acme-challenge/;
        try_files $uri =404;
    }

    location / {
        return 301 https://$BASE_URL$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name $OLD_BASE_URL www.$OLD_BASE_URL;

    ssl_certificate     /app/letsencrypt/certificates/live/$BASE_URL/fullchain.pem;
    ssl_certificate_key /app/letsencrypt/certificates/live/$BASE_URL/privkey.pem;

    location / {
        return 301 https://$BASE_URL$request_uri;
    }
}